Microverse HTML, CSS, JS Capstone project 1
mumo-esther/microverse-capstone-1 pull request #1
Opened 2023-02-07 13:36 UTC by mumo-esther

2023-02-07 15:02 UTC, iambenkis requested changes
Hello @mumo-esther , 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃 

## Highlights 💪 
- Innovative idea in a good-looking website
- good UI design
- no linter errors
- correct github flow is used
- good PR description


## Required Changes ♻️

- [ ] Kindly make sure you add a complete documentation in your project  , you can you this as an [example of a complete documentation](https://github.com/iambenkis/Global-summit-GMIS-/blob/master/README.md)

_Check other comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 15:02 UTC, iambenkis commented on README.md
> -<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Good job setting up  a README template for your project :clap:  , however  your README should contain a video presentation of you describing your project, kindly use ```loom``` or ```Zoom``` for that. :smile:

2023-02-07 15:02 UTC, iambenkis commented on README.md
- [ ] Kindly make sure your README file has a demo link that brings to the deployed website, for more information about deployment :+1: follow this l[ink](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/deploy/lesson_deploy_github_pages.md)

2023-02-07 15:02 UTC, iambenkis commented on README.md
- [ ] As you have used someone else design, it is important to give a credit to him/her as a privilege. This helps anyone who visits your website but is interested in the design you have followed get to know the source 💡. Moreover, it is among the project requirements to give credit to [Cindy Shin](https://www.behance.net/adagio07) the author of the original design you used. Please add her here in the Acknowledgement section and the link to the design. 😃 👍

2023-02-07 15:02 UTC, iambenkis commented on index.html
>          <article class="program-item flex-row-center bg-light-black">
Great job 👏 👏. Seriously, your design looks great 💯. A small adjustment I would suggest you make is about the main program section. The item card do not have the same size :+1: . 
It is important to pay attention to all details even the small ones because it is what makes you outstanding 😉

### Your design

![Screenshot from 2023-02-07 16-23-26](https://user-images.githubusercontent.com/80458199/217277558-7437eba7-a4f9-424c-a533-1998b16a7c90.png)


### Template design

![Screenshot from 2023-02-07 16-37-08](https://user-images.githubusercontent.com/80458199/217277647-85e49479-6e05-41ae-8b97-10a5ac40c5ea.png)


- [ ] Also make sure you add the ```hover``` property on each card as it may be noticed in the Template design
### Example 
```bash
.program-item:hover {
   .....
}
```

2023-02-07 15:02 UTC, iambenkis commented on js/app.js
> -      'Lorem ipsum, dolor sit amet adipisicing elit. Deleniti, molestias.',
Great job 👏 👏. Seriously, your design looks great 💯. A small adjustment I would suggest you make is about the layout of the speaker section :speak_no_evil:  
It is important to pay attention to all details even the small ones because it is what makes you outstanding 😉

### Your design 

![Screenshot from 2023-02-07 16-23-51](https://user-images.githubusercontent.com/80458199/217278849-4d431557-97f8-4122-8271-4d9e7ca95bc5.png)



### Template design
![Screenshot from 2023-02-07 16-37-32](https://user-images.githubusercontent.com/80458199/217278857-97cd102c-900d-4d7c-a5b4-cb63aac40fe1.png)

2023-02-07 15:02 UTC, iambenkis commented on index.html
>            </p>
- [ ] Kindly make sure that the background you have in the `main program` section stick to the template design. 
- [ Note ] Always see the given template or Figma design as a client needs you have to respect :+1: 
 The background should be an image, Kindly improve that :+1: 

![Screenshot from 2023-02-07 16-57-54](https://user-images.githubusercontent.com/80458199/217280504-14420cde-7ad2-41f6-9dbb-f27e0921f9a8.png)

2023-02-08 09:18 UTC, binhussen approved these changes
Hi @mumo-esther, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 09:18 UTC, binhussen commented on README.md
> +
- [Optional] Great job for adding a live demo and the loom link 👍👍, I think it would be better to use the live demo link in the prepared place from the [template](https://github.com/microverseinc/readme-template#live-demo) and add the loom video on the pull request summary 👍👍

2023-02-08 09:18 UTC, binhussen commented on style.css
> +  background-image: url(./Assets/images/Program-bg.jpg);
- [Optional] Great Job for updating the previous suggestions.👍  I think you missed the bg image spelling `Assets/images/program-bg.jpg` so it is better to use only small letters for the asset file👍👍

2023-02-08 09:18 UTC, binhussen commented on about.html
> +        <li><a href="#" class="English light-grey upperside-item">English</a></li>
- [Optional] Kindly you for the font style and color are not the same and you have loosed margin and padding from the mobile version, Kindly stick to the given design as much as possible to have a better [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 👍👍

https://user-images.githubusercontent.com/52010789/217487160-d820c983-3d17-4734-a9e9-a3c46d664cbf.mp4

2023-02-08 12:42 UTC, merged